package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Student profile entity for PathPilot AI to store user profile data locally.
 */
@Entity(tableName = "students")
data class StudentProfile(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 1L,
    val name: String = "Alex Chen",
    val courseBranch: String = "Computer Science & Engineering",
    val year: String = "2nd Year",
    val careerGoal: String = "Software Engineer",
    val currentSkills: String = "Python, Git, Basic C++",
    val dailyAvailableHours: Double = 3.5, // e.g. 3.5 hours per day
    val preferredStudyHours: String = "Evening (6:00 PM - 10:00 PM)",
    val targetDailyMinutes: Int = 210,
    val bio: String = "CSE student focusing on backend development, algorithms, and AI tools."
)

typealias Student = StudentProfile

/**
 * Task entity storing student academic, skill, and routine tasks locally.
 */
@Entity(tableName = "tasks")
data class Task(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val taskName: String,
    val subjectCategory: String = "Assignment", // Assignment, Exam Prep, Skill Practice, Project, Routine
    val deadlineTimestamp: Long = System.currentTimeMillis() + 86400000L, // Epoch millis
    val deadlineDesc: String = "Tomorrow", // "Tomorrow 5:00 PM", "Friday", etc.
    val importance: Int = 3, // 1 to 5 (Very Low to Critical)
    val estimatedDurationMinutes: Int = 60, // e.g. 120 mins
    val careerValue: Int = 2, // 1 to 4 (Low to Top Tier)
    val canBeSplit: Boolean = true,
    val status: String = "Pending", // "Pending", "In Progress", "Completed", "Missed"
    val priorityScore: Double = 0.0,
    val remainingTimeMinutes: Int = 0,
    val completedAt: Long? = null,
    val notes: String = ""
)

typealias TaskItem = Task

/**
 * Skill entity for the Career Skill Roadmap.
 */
@Entity(tableName = "skills")
data class SkillItem(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val name: String,
    val category: String, // Core, Backend, Frontend, Cloud, AI, Soft Skill
    val careerGoal: String, // "Software Engineer", "AI/ML Engineer", etc.
    val stepOrder: Int,
    val status: String = "Recommended", // "Recommended", "In Progress", "Mastered"
    val progressPercent: Int = 0, // 0 to 100
    val estimatedWeeks: Int = 2,
    val description: String = ""
)

/**
 * Study session logging time spent on tasks.
 */
@Entity(tableName = "study_sessions")
data class StudySession(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val taskId: Long? = null,
    val taskName: String,
    val category: String,
    val durationMinutes: Int,
    val timestamp: Long = System.currentTimeMillis(),
    val completed: Boolean = true,
    val notes: String = ""
)

/**
 * Daily progress analytics record.
 */
@Entity(tableName = "progress")
data class ProgressRecord(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val dateString: String, // e.g. "2026-09-15"
    val completedCount: Int = 0,
    val pendingCount: Int = 0,
    val missedCount: Int = 0,
    val totalMinutesStudied: Int = 0,
    val productivityScore: Int = 0 // 0 to 100
)

/**
 * Data class representing a time-blocked scheduled task slot generated by the Adaptive AI Planner.
 */
data class ScheduleSlot(
    val slotId: String,
    val taskId: Long,
    val taskName: String,
    val category: String,
    val startTime: String, // e.g. "9:00 AM"
    val endTime: String,   // e.g. "11:00 AM"
    val durationMinutes: Int,
    val priorityScore: Double,
    val isSplitPart: Boolean = false,
    val splitPartInfo: String? = null, // e.g. "Part 1 of 2"
    val isMissed: Boolean = false,
    val isCompleted: Boolean = false,
    val explanationReason: String = ""
)
